export const DOBOK_V9_COMBINATIONS = {
  "female-chest-2button": {
    key: "female-chest-2button",
    gender: "female",
    style: "chest",
    sleeve: "2button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-chest-2button/female-chest-2button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-2button/female-chest-2button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-2button/female-chest-2button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-2button/female-chest-2button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-2button/female-chest-2button-pants-texture.png"),
  },
  "female-chest-3button": {
    key: "female-chest-3button",
    gender: "female",
    style: "chest",
    sleeve: "3button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-chest-3button/female-chest-3button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-3button/female-chest-3button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-3button/female-chest-3button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-3button/female-chest-3button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-3button/female-chest-3button-pants-texture.png"),
  },
  "female-chest-plain": {
    key: "female-chest-plain",
    gender: "female",
    style: "chest",
    sleeve: "plain",
    base: require("../../../../assets/dobok/v9/combinations/female/female-chest-plain/female-chest-plain.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-plain/female-chest-plain-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-plain/female-chest-plain-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-chest-plain/female-chest-plain-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-chest-plain/female-chest-plain-pants-texture.png"),
  },
  "female-diagonal-waist-2button": {
    key: "female-diagonal-waist-2button",
    gender: "female",
    style: "diagonal-waist",
    sleeve: "2button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-2button/female-diagonal-waist-2button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-2button/female-diagonal-waist-2button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-2button/female-diagonal-waist-2button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-2button/female-diagonal-waist-2button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-2button/female-diagonal-waist-2button-pants-texture.png"),
  },
  "female-diagonal-waist-3button": {
    key: "female-diagonal-waist-3button",
    gender: "female",
    style: "diagonal-waist",
    sleeve: "3button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-3button/female-diagonal-waist-3button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-3button/female-diagonal-waist-3button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-3button/female-diagonal-waist-3button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-3button/female-diagonal-waist-3button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-3button/female-diagonal-waist-3button-pants-texture.png"),
  },
  "female-diagonal-waist-plain": {
    key: "female-diagonal-waist-plain",
    gender: "female",
    style: "diagonal-waist",
    sleeve: "plain",
    base: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-plain/female-diagonal-waist-plain.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-plain/female-diagonal-waist-plain-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-plain/female-diagonal-waist-plain-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-plain/female-diagonal-waist-plain-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-diagonal-waist-plain/female-diagonal-waist-plain-pants-texture.png"),
  },
  "female-straight-2button": {
    key: "female-straight-2button",
    gender: "female",
    style: "straight",
    sleeve: "2button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-straight-2button/female-straight-2button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-2button/female-straight-2button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-2button/female-straight-2button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-2button/female-straight-2button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-2button/female-straight-2button-pants-texture.png"),
  },
  "female-straight-3button": {
    key: "female-straight-3button",
    gender: "female",
    style: "straight",
    sleeve: "3button",
    base: require("../../../../assets/dobok/v9/combinations/female/female-straight-3button/female-straight-3button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-3button/female-straight-3button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-3button/female-straight-3button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-3button/female-straight-3button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-3button/female-straight-3button-pants-texture.png"),
  },
  "female-straight-plain": {
    key: "female-straight-plain",
    gender: "female",
    style: "straight",
    sleeve: "plain",
    base: require("../../../../assets/dobok/v9/combinations/female/female-straight-plain/female-straight-plain.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-plain/female-straight-plain-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-plain/female-straight-plain-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/female/female-straight-plain/female-straight-plain-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/female/female-straight-plain/female-straight-plain-pants-texture.png"),
  },
  "male-straight-2button": {
    key: "male-straight-2button",
    gender: "male",
    style: "straight",
    sleeve: "2button",
    base: require("../../../../assets/dobok/v9/combinations/male/male-straight-2button/male-straight-2button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-2button/male-straight-2button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-2button/male-straight-2button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-2button/male-straight-2button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-2button/male-straight-2button-pants-texture.png"),
  },
  "male-straight-3button": {
    key: "male-straight-3button",
    gender: "male",
    style: "straight",
    sleeve: "3button",
    base: require("../../../../assets/dobok/v9/combinations/male/male-straight-3button/male-straight-3button.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-3button/male-straight-3button-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-3button/male-straight-3button-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-3button/male-straight-3button-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-3button/male-straight-3button-pants-texture.png"),
  },
  "male-straight-plain": {
    key: "male-straight-plain",
    gender: "male",
    style: "straight",
    sleeve: "plain",
    base: require("../../../../assets/dobok/v9/combinations/male/male-straight-plain/male-straight-plain.png"),
    topMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-plain/male-straight-plain-top-mask.png"),
    topTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-plain/male-straight-plain-top-texture.png"),
    pantsMask: require("../../../../assets/dobok/v9/combinations/male/male-straight-plain/male-straight-plain-pants-mask.png"),
    pantsTexture: require("../../../../assets/dobok/v9/combinations/male/male-straight-plain/male-straight-plain-pants-texture.png"),
  }
};

export const DOBOK_V9_COMBO_LIST = Object.values(DOBOK_V9_COMBINATIONS);

export const DOBOK_V9_EMBROIDERY_ASSETS = {
  chestSource: require("../../../../assets/dobok/v9/embroidery/chest-source.png"),
  chestTintMask: require("../../../../assets/dobok/v9/embroidery/chest-tint-mask.png"),
  cloudSource: require("../../../../assets/dobok/v9/embroidery/cloud-source.png"),
  placementReference: require("../../../../assets/dobok/v9/embroidery/placement-reference.png"),
};

export const DOBOK_V9_FABRIC_REFERENCE_IMAGES = {
  fabricA: require("../../../../assets/dobok/v9/fabrics/reference/fabric-a-chart.png"),
  fabricB: require("../../../../assets/dobok/v9/fabrics/reference/fabric-b-chart.png"),
};
