export const DOBOK_V9_COMBINATIONS = {
"female-chest-2button": {
  key: "female-chest-2button",
  gender: "female",
  style: "chest",
  sleeve: "2button",
  canvasWidth: 1024,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-2button/wrist-cloud-mask.png"),
},
"female-chest-3button": {
  key: "female-chest-3button",
  gender: "female",
  style: "chest",
  sleeve: "3button",
  canvasWidth: 1024,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-3button/wrist-cloud-mask.png"),
},
"female-chest-plain": {
  key: "female-chest-plain",
  gender: "female",
  style: "chest",
  sleeve: "plain",
  canvasWidth: 1022,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-chest-plain/wrist-cloud-mask.png"),
},
"female-diagonal-waist-2button": {
  key: "female-diagonal-waist-2button",
  gender: "female",
  style: "diagonal-waist",
  sleeve: "2button",
  canvasWidth: 1022,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-2button/wrist-cloud-mask.png"),
},
"female-diagonal-waist-3button": {
  key: "female-diagonal-waist-3button",
  gender: "female",
  style: "diagonal-waist",
  sleeve: "3button",
  canvasWidth: 1022,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-3button/wrist-cloud-mask.png"),
},
"female-diagonal-waist-plain": {
  key: "female-diagonal-waist-plain",
  gender: "female",
  style: "diagonal-waist",
  sleeve: "plain",
  canvasWidth: 1022,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-diagonal-waist-plain/wrist-cloud-mask.png"),
},
"female-straight-2button": {
  key: "female-straight-2button",
  gender: "female",
  style: "straight",
  sleeve: "2button",
  canvasWidth: 1023,
  canvasHeight: 1537,
  base: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-2button/wrist-cloud-mask.png"),
},
"female-straight-3button": {
  key: "female-straight-3button",
  gender: "female",
  style: "straight",
  sleeve: "3button",
  canvasWidth: 1086,
  canvasHeight: 1448,
  base: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-3button/wrist-cloud-mask.png"),
},
"female-straight-plain": {
  key: "female-straight-plain",
  gender: "female",
  style: "straight",
  sleeve: "plain",
  canvasWidth: 1086,
  canvasHeight: 1448,
  base: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/female-straight-plain/wrist-cloud-mask.png"),
},
"male-straight-2button": {
  key: "male-straight-2button",
  gender: "male",
  style: "straight",
  sleeve: "2button",
  canvasWidth: 1024,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-2button/wrist-cloud-mask.png"),
},
"male-straight-3button": {
  key: "male-straight-3button",
  gender: "male",
  style: "straight",
  sleeve: "3button",
  canvasWidth: 1022,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-3button/wrist-cloud-mask.png"),
},
"male-straight-plain": {
  key: "male-straight-plain",
  gender: "male",
  style: "straight",
  sleeve: "plain",
  canvasWidth: 1024,
  canvasHeight: 1536,
  base: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/base.png"),
  topMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/top-mask.png"),
  topTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/top-texture.png"),
  pantsMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/pants-mask.png"),
  pantsTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/pants-texture.png"),
  neckMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/neck-mask.png"),
  neckTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/neck-texture.png"),
  wristMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/wrist-mask.png"),
  wristTexture: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/wrist-texture.png"),
  neckCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/neck-cloud-mask.png"),
  wristCloudMask: require("../../../../assets/images/dobok-showroom/v12/male-straight-plain/wrist-cloud-mask.png"),
}
};

export const DOBOK_V9_COMBO_LIST = Object.values(DOBOK_V9_COMBINATIONS);

// 가슴 자수는 용·음양·수 문양의 투명 틴트 마스크를 사용합니다.
// 목깃·소매 구름은 각 조합의 전체 캔버스 마스크를 사용하므로 좌표 설정이 필요 없습니다.
export const DOBOK_V9_EMBROIDERY_ASSETS = {
  chestSource: require("../../../../assets/images/dobok-showroom/v12/embroidery/chest-dragon-yinyang-longevity-source.png"),
  chestTintMask: require("../../../../assets/images/dobok-showroom/v12/embroidery/chest-dragon-yinyang-longevity-mask.png"),
  cloudSource: require("../../../../assets/dobok/v9/embroidery/cloud-source.png"),
  placementReference: require("../../../../assets/dobok/v9/embroidery/placement-reference.png"),
};

export const DOBOK_V9_FABRIC_REFERENCE_IMAGES = {
  fabricA: require("../../../../assets/dobok/v9/fabrics/reference/fabric-a-chart.png"),
  fabricB: require("../../../../assets/dobok/v9/fabrics/reference/fabric-b-chart.png"),
};
