import profilePlaceholder from "../../../assets/images/profile-placeholder.png";

export const avatarImages = {
  avatar1: require("../../../assets/images/avatar1.png"),
  avatar2: require("../../../assets/images/avatar2.png"),
  avatar3: require("../../../assets/images/avatar3.png"),
  avatar4: require("../../../assets/images/avatar4.png"),
  avatar5: require("../../../assets/images/avatar5.png"),
  avatar6: require("../../../assets/images/avatar6.png"),
  avatar7: require("../../../assets/images/avatar7.png"),
  avatar8: require("../../../assets/images/avatar8.png"),
  avatar9: require("../../../assets/images/avatar9.png"),
  avatar10: require("../../../assets/images/avatar10.png"),
  avatar11: require("../../../assets/images/avatar11.png"),
  avatar12: require("../../../assets/images/avatar12.png"),
  avatar13: require("../../../assets/images/avatar13.png"),
  avatar14: require("../../../assets/images/avatar14.png"),
  avatar15: require("../../../assets/images/avatar15.png"),
  avatar16: require("../../../assets/images/avatar16.png"),
  avatar17: require("../../../assets/images/avatar17.png"),
  avatar18: require("../../../assets/images/avatar18.png"),
  avatar19: require("../../../assets/images/avatar19.png"),
  avatar20: require("../../../assets/images/avatar20.png"),
  avatar21: require("../../../assets/images/avatar21.png"),
  avatar22: require("../../../assets/images/avatar22.png"),
  avatar23: require("../../../assets/images/avatar23.png"),
  avatar24: require("../../../assets/images/avatar24.png"),
  avatar25: require("../../../assets/images/avatar25.png"),
};

export const avatarGroups = {
  animal: [
    "avatar1",
    "avatar2",
    "avatar3",
    "avatar4",
    "avatar5",
    "avatar6",
    "avatar7",
    "avatar8",
    "avatar9",
    "avatar10",
    "avatar11",
    "avatar12",
    "avatar13",
    "avatar14",
    "avatar21",
    "avatar22",
    "avatar23",
    "avatar24",
    "avatar25",
  ],
  person: ["avatar15", "avatar16", "avatar17", "avatar18", "avatar19", "avatar20"],
};

export const mypageImages = {
  profilePlaceholder,
  cameraIcon: require("../../../assets/images/camera-icon.png"),
  yudanjaIcon: require("../../../assets/images/yudanja-icon.png"),
  yudanjaCardBg: require("../../../assets/images/yudanja-card-bg.png"),
  yudanjaCardBackImage: require("../../../assets/images/yudanja-card-back.png"),
  yudanjaEmblemFrame: require("../../../assets/images/yudanja-emblem-frame.png"),
  yudanjaProfileCardBg: require("../../../assets/images/yudanja-profile-card-bg.png"),
  goalSettingIcon: require("../../../assets/images/goal-setting-icon.png"),
  paymentBankIcon: require("../../../assets/images/payment-bank-icon.png"),
  paymentSeoulPayIcon: require("../../../assets/images/payment-seoulpay-icon.png"),
  paymentCardIcon: require("../../../assets/images/payment-card-icon.png"),
};